bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.5.post6
rdf_sha256: a659b79870838c00b9f06f2127f0b334fdbe5aea1f6b856912de6552f1d4f8f3
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.5post6
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_spec_version: 0.4.5post6
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: cannot reshape array of size 401117 into shape (1,304,512,33)
    name: reproduced test outputs from test inputs
    status: failed
    traceback: ["  File \"/usr/share/miniconda/envs/6338615/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 127, in test_resource\n    expected = [np.load(str(out_path)) for out_path
        in model.test_outputs]\n", "  File \"/usr/share/miniconda/envs/6338615/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 127, in <listcomp>\n    expected = [np.load(str(out_path)) for out_path
        in model.test_outputs]\n", "  File \"/usr/share/miniconda/envs/6338615/lib/python3.7/site-packages/numpy/lib/npyio.py\",
        line 453, in load\n    pickle_kwargs=pickle_kwargs)\n", "  File \"/usr/share/miniconda/envs/6338615/lib/python3.7/site-packages/numpy/lib/format.py\",
        line 785, in read_array\n    array.shape = shape\n"]
  ilastik:
  - {bioimageio_core_version: 0.5.1, bioimageio_spec_version: 0.4.5post3, error: null,
    name: reproduce test outputs with ilastik <todo version> (draft) using tensorflow_saved_model_bundle
      weights, reason: null, status: passed, traceback: null}
