{
  "bio-core-mix": {
    "py3.8.12_onnx": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "Output and expected output disagree:\n \nArrays are not almost equal to 4 decimals\n\nMismatched elements: 21229 / 2097152 (1.01%)\nMax absolute difference: 0.00181919\nMax relative difference: 1.\n x: array([[[[2.5241e-01, 1.6527e-01, 1.3083e-01, ..., 3.0019e-01,\n          2.5673e-01, 2.9213e-01],\n         [1.1550e-01, 3.0777e-02, 1.8271e-02, ..., 6.1141e-02,...\n y: array([[[[2.5239e-01, 1.6525e-01, 1.3081e-01, ..., 3.0017e-01,\n          2.5671e-01, 2.9212e-01],\n         [1.1548e-01, 3.0769e-02, 1.8265e-02, ..., 6.1130e-02,...",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.8.12_pytorch_script": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "name": "reproduced test outputs",
        "success": true
      }
    ],
    "py3.8.12_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "name": "reproduced test outputs",
        "success": true
      }
    ],
    "py3.8.12_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format tensorflow_saved_model_bundle not among weight formats listed in model: ['onnx', 'pytorch_script', 'pytorch_state_dict']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 56, in test_resource\n    prediction_pipeline = create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 142, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 61, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.9.7_onnx": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "Output and expected output disagree:\n \nArrays are not almost equal to 4 decimals\n\nMismatched elements: 21229 / 2097152 (1.01%)\nMax absolute difference: 0.00181919\nMax relative difference: 1.\n x: array([[[[2.5241e-01, 1.6527e-01, 1.3083e-01, ..., 3.0019e-01,\n          2.5673e-01, 2.9213e-01],\n         [1.1550e-01, 3.0777e-02, 1.8271e-02, ..., 6.1141e-02,...\n y: array([[[[2.5239e-01, 1.6525e-01, 1.3081e-01, ..., 3.0017e-01,\n          2.5671e-01, 2.9212e-01],\n         [1.1548e-01, 3.0769e-02, 1.8265e-02, ..., 6.1130e-02,...",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.9.7_pytorch_script": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "name": "reproduced test outputs",
        "success": true
      }
    ],
    "py3.9.7_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "name": "reproduced test outputs",
        "success": true
      }
    ],
    "py3.9.7_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format tensorflow_saved_model_bundle not among weight formats listed in model: ['onnx', 'pytorch_script', 'pytorch_state_dict']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 56, in test_resource\n    prediction_pipeline = create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 142, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 61, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ]
  }
}