error: null
name: bioimageio.spec static validation
nested_errors: {}
source_name: '{name: MitoEM Challenge: Large-scale 3D Mitochondria Instance Segmentation,
  ...}'
traceback: null
warnings: {type: Unrecognized type 'dataset'. Validating as rdf.}
