bioimageio_spec_version: 0.4.8.post1
rdf_sha256: a7bbf6197200681479e0b5a6c8ca0e13610f9e35106fa55e7f1ebff004a4d06f
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {}
  - error: No module named 'tqdm'
    name: import test_resource from test environment
    status: failed
    traceback: ["  File \"/home/runner/work/collection-bioimage-io/collection-bioimage-io/scripts/dynamic_validation.py\",
        line 41, in main\n    from bioimageio.core.resource_tests import test_resource\n",
      "  File \"/home/runner/micromamba-root/envs/7274276/lib/python3.10/site-packages/bioimageio/core/__init__.py\",
        line 13, in <module>\n    from .prediction_pipeline import create_prediction_pipeline\n",
      "  File \"/home/runner/micromamba-root/envs/7274276/lib/python3.10/site-packages/bioimageio/core/prediction_pipeline/__init__.py\",
        line 2, in <module>\n    from ._prediction_pipeline import PredictionPipeline,
        create_prediction_pipeline\n", "  File \"/home/runner/micromamba-root/envs/7274276/lib/python3.10/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 12, in <module>\n    from ._stat_state import StatsState\n", "  File
        \"/home/runner/micromamba-root/envs/7274276/lib/python3.10/site-packages/bioimageio/core/prediction_pipeline/_stat_state.py\",
        line 3, in <module>\n    from tqdm import tqdm\n"]
  deepimagej:
  - {bioimageio_spec_version: 0.4.8post1, error: rdf does not have a compatible weight
      format, name: Initial compatibility checks with DeepImageJ, status: failed}
  ilastik:
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: load resource description
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - {error: null, name: has expected resource type, status: passed, traceback: null}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: All URLs and paths available
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: "Output and expected output disagree:\n \nArrays are not almost equal to
      4 decimals\n\nMismatched elements: 8695 / 262144 (3.32%)\nMax absolute difference:
      0.00055829\nMax relative difference: 0.00579266\n x: array([[[[[3.4632e-01,
      3.8060e-01, 4.4760e-01, ..., 7.0277e-02,\n           7.4078e-02, 1.3726e-01],\n
      \         [3.4271e-01, 3.7405e-01, 4.7610e-01, ..., 3.2165e-02,...\n y: array([[[[[3.4634e-01,
      3.8058e-01, 4.4760e-01, ..., 7.0247e-02,\n           7.4062e-02, 1.3723e-01],\n
      \         [3.4274e-01, 3.7407e-01, 4.7612e-01, ..., 3.2150e-02,..."
    name: reproduce test outputs from test inputs
    status: failed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: load resource description
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: All URLs and paths available
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: "Output and expected output disagree:\n \nArrays are not almost equal to
      4 decimals\n\nMismatched elements: 8695 / 262144 (3.32%)\nMax absolute difference:
      0.00055829\nMax relative difference: 0.00579266\n x: array([[[[[3.4632e-01,
      3.8060e-01, 4.4760e-01, ..., 7.0277e-02,\n           7.4078e-02, 1.3726e-01],\n
      \         [3.4271e-01, 3.7405e-01, 4.7610e-01, ..., 3.2165e-02,...\n y: array([[[[[3.4634e-01,
      3.8058e-01, 4.4760e-01, ..., 7.0247e-02,\n           7.4062e-02, 1.3723e-01],\n
      \         [3.4274e-01, 3.7407e-01, 4.7612e-01, ..., 3.2150e-02,..."
    name: reproduce test outputs from test inputs
    status: failed
    traceback: null
    warnings: {}
